name: .NET Core Desktop CI + Docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  # Use Linux runner to work with Docker

    env:
      Solution_Name: GitAction/GitAction.sln
      Test_Project_Path: GitAction/TestProject1/TestProject1.csproj
      Wap_Project_Path: GitAction/WebApplication1/WebApplication1.csproj
      Docker_Image_Name: webapp-test:${{ matrix.configuration }}
      Docker_Registry: ghcr.io
      Docker_Repository: aleksmorozova/githubdeploy  # Lowercase name here
      Base64_Encoded_Pfx: ${{ secrets.Base64_Encoded_Pfx }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore GitAction/GitAction.sln

    - name: Build solution
      run: dotnet build GitAction/GitAction.sln --configuration ${{ matrix.configuration }}

    - name: Run unit tests
      run: dotnet test GitAction/TestProject1/TestProject1.csproj --configuration ${{ matrix.configuration }}

    # Docker: Build image (set context to the root folder of the repo)
    - name: Docker Build (.NET Web App)
      working-directory: ./  # Set working directory to the root folder of the repo (GitHubDeploy)
      run: docker build -t ghcr.io/aleksmorozova/githubdeploy/webapp-test:${{ matrix.configuration }} -f GitAction/Dockerfile .

    # Docker: Authenticate to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Docker: Push the image to GitHub Container Registry
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/aleksmorozova/githubdeploy/webapp-test:${{ matrix.configuration }}

    # Docker: Run container for verification (optional)
    - name: Docker Run container
      run: |
        docker run -d -p 8080:80 --name temp-runner ghcr.io/aleksmorozova/githubdeploy/webapp-test:${{ matrix.configuration }}
        docker ps

    # Docker Cleanup
    - name: Docker Cleanup (remove temp container)
      run: |
        docker stop temp-runner
        docker rm temp-runner
