name: .NET Core CI + Docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: GitAction/GitAction.sln
      Test_Project_Path: GitAction/TestProject1/TestProject1.csproj
      Wap_Project_Path: GitAction/WebApplication1/WebApplication1.csproj
      Docker_Image_Name: webapp-test:${{ matrix.configuration }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Run unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}

    - name: Docker Build (.NET Web App)
      run: docker build -t ${{ env.Docker_Image_Name }} --file Dockerfile .

    - name: Docker Run container
      run: |
        docker run -d -p 8080:80 --name temp-runner ${{ env.Docker_Image_Name }}
        docker ps

    - name: Docker Cleanup (remove temp container)
      run: |
        docker stop temp-runner
        docker rm temp-runner
