name: .NET Core CI + Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: GitAction.sln
      Test_Project_Path: TestProject1/TestProject1.csproj
      Wap_Project_Path: WebApplication1/WebApplication1.csproj
      Docker_Image_Name: webapp-test:${{ matrix.configuration }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}
      working-directory: GitAction

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}
      working-directory: GitAction

    - name: Run unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}
      working-directory: GitAction

    - name: Docker Build (.NET Web App)
      run: docker build -t ${{ env.Docker_Image_Name }} -f Dockerfile .
      working-directory: GitAction

    - name: Docker Run container
      run: |
        docker run -d -p 8080:80 --name temp-runner ${{ env.Docker_Image_Name }}
        docker ps

    - name: Docker Cleanup
      run: |
        docker stop temp-runner
        docker rm temp-runner
